### ISSUE TITLE
information request

### ISSUE THREAD

**Issue by dsptech** [LilyGO/TTGO-TQ-0.91#1]
Hi, I need more information about TTGO-TQ-0.91.
Is it available a schematics ?
Thank you.
Regard.

**Comment by tomfleet** [comment]
Hi, 

@dsptech , @LilyGO 

Why was this issue closed without comment? The schematic would be very helpful to people who have purchased this board. 

Is it available?

Kind Regards,

Tom

**Comment by dsptech** [comment]
Hi @tomfleet ,
the question was unanswered for more than one month.
I think now that @LilyGO  is not interested to answer a such kind of questions.
So, I closed the question and changed kind of product for my projects.
Regards.

**Comment by tomfleet** [comment]
Hi @dsptech,

That is a fair course of action given lack of support.

I will keep you in mind if I do happen to find a schematic.

BR,

Tom

**Comment by LilyGO** [comment]
[T13_V1.0.pdf](https://github.com/LilyGO/TTGO-TQ-0.91/files/2635526/T13_V1.0.pdf)

**Comment by LilyGO** [comment]
@dsptech @tomfleet I am very sorry, I did not respond in time. This is the schematic

**Comment by tomfleet** [comment]
Many thanks for your reply @LilyGo, it still helps me a lot!
